services:
  - docker

branches:
  only:
  - exercise-8

script:
  - #docker build --tag todo-app-dev --target development .
  - #docker build --tag todo-app-test --target test .
  - docker build --tag todo-app-prod:$TRAVIS_COMMIT --target production  .
  - #docker run -e MY_SECRET -e SERVER_TOKEN -e DEVELOPER_API_KEY -e FLASK_APP -e FLASK_ENV todo-app-test:latest
  - echo "Push Production image to Docker Hub"
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $DOCKER_USER/todo-app-prod:$TRAVIS_COMMIT

  - #echo "Push the TODO list to Heroku"
  - #docker pull $DOCKER_USER/todo-app-prod:$TRAVIS_COMMIT
  - #docker tag $DOCKER_USER/todo-app-prod:$TRAVIS_COMMIT registry.heroku.com/sixela-app/web
  - #heroku container:login
  - #docker push registry.heroku.com/sixela70/web
  - #heroku container:release web -a sixela-app

env:  
  global:
    - DOCKER_USER=sixela70
    - DOCKER_PWD=,SyYBiFp2St68H9      
    - FLASK_APP=todo_app/app
    - FLASK_ENV=development
    - # Encrypted MY_SECRET SERVER_TOKEN DEVELOPER_API_KEY 
    - secure: yOVMv6oWPNOKVLNI9ZdRDeACQkUCa0Dh2R88VMjT6u3jUhCT+OP+WRxBmAfz/87J/IsSaQ9IbXt3yhsQykLex6mC3bLCHh8F8qsc4uwU9lbdWco7yA9rWDupEgAAdopYWS6jyVnVzUjxnwTwn4mWzb94mkwVWPAjtiUjUwLgtEKqvNRYFyppxcqRCqRndToDb2LIPGCv1Lv4U1wtYqOhx09fzQdCg5HqcMQpbkaiBcGlXxgXqa4JVaLrqTHhlyEv/PktVHtqcuPO2gs8SkRN9M1K6BuZA8Jw4yVT2g6wAGj48SqhAyS8hjvr/0zhJIDBmlWbWipFZHCm4wvO7iNXS5MmUNbiU945aBrwCE3EtyXcHUJw5LdNFVaQrlWz2bu0VeqRVJtWk09PtXOP5nRYoxoiN6LSLMkD4mIk3psCsRO24RGZ6IDvzGn3FbqnRuJk3KPd81j7SwQuYboMZDV2FwnmxLmsF0ISsAjxPa9VB3GNY0jhhfABYROEubnhFvw6QpTH1+QZqA6HD1zurZwXn2fekflARw5nbffp5607kmx5iYJUKDB/BvYSzte14DXWdsg6mCr+N/jcWUOzt3W/g0W5lx6rI3dX3BmiOotH6vLCpCUNLz8kSBMaiQJI/CHO8qd2gqwQV7mBkdcGuzGM1MAqRD1jkTRZvxw74ifSJEM=
    - secure: Pm/l8yhe1+NJbydk84kvRMEmGB4uFurH+e1thmEApYpAI5H1GZ4F/eq7LUBJdZHBrNpNgcCaU4m6y2BSy5K9cbDK+1ecFBZLByHdyYsNxAjAu/YQashj5kJi/u6rumuiLX+kXm6OLp/lsgxI+QuZhBQlF/Nv8wag2nG5IG16rmZRI1dvgIT1gmEcQOKCDrL2Xg2zuNjL930sdK3H3iltN1Mme0eN50UTgOkNqa4IMOZiP4xOwd1v71Hom69Fzq4nTmoXMj8Tiw61uNZ/3AxHwO34jdfU16trXsMIGi+9jIsFHAgAJBDm8scyw7KAPL4iGOpFzX9WmRdXl270+egiNuTr0Eily59fVyqqUgknWzRk+OfwOqI5vZAFxU0Mq+GOAlrjZ/QW5S9V5BqOcQvqhxoahUr4TDVUgmutJ8eWbejXOUC5ODCSck6stJeRNQiu8LaD8Q+UiWWUg/0p9DC5cGynsSwfhxpxqIlhmzzfv02ljVpV/+IbY8a/ax1tK82HbYQHb2XpkwUDWySlMBl4i2pVu3RVBxm/cXrmEgQpGXWBdy1Ifut77VaPpJs79vE4HJr9E0yrawuMQGeAwJURfdrfw3vuytNZGAUS0gRe9cVXWAI2UTxBCDEUtqwNq9XMfbtPlD+5ZhNxeNVKFm/KzlFpxgyUBD23Sh90VZsKTpc=
    - secure: HVHECbDzucKtEgqHg9NCUy+2FsajMYJhhT2K2JUa9I1+mid2KVYUHF3gnNS3VgkenhlklpkBC2NPKXKt0SrfiBMmMvj4AbVVRlVcIJXz1j7vGP8PCQAp4jdRnRGFSMMf+Y5vg2XNQ2Ecb6mnbhCt6YYCDbzMUVwLbYEEks7jEHRTPhH2hh6FCExggSGwv+dIUcwXimbpQ/yR1OfiWB5sDMFkQ4hGpBKx3mssXhIq+1uGXln1dPvH6HQf5PvSOVGIls7VNVl0YR3p8Y4b+4UaQwPek6seCnb9mTq1+jmJrZJocWqnbviJmDm5B/wrM4jWHh0bk4WgtAyWlqOBT0DfZMKQdJsp3u3CSnMnEDCBA7YXhJW0nLW3eGvaAb1WBNZsEPNWyQiJ4V3nYOhBMy+ZTWFFTXfuStWjRdA9i8dnJ61gwRKNXSN7IYaGQSSvhy/Y8YDkcUz9sNJQmU1BhGZUYuqruxhAgfvJTcWLti/fMdVrjbqqdCJaKJpHtu3rQIKSK5N0Igw2x5IoDFRhHk1xJKLntliZQphTLpXwf92hP3HM3VaR9qyMyAUZtWa4niDOSOkaemUeiSjWpPDwUVF/fdolqZlVs04HkAClHxVuU7utWCzWz5PU3AQki0qt9KXT98LdJQ5IFe0BjZKFHAIdNa531Ir3HZGyG6+lu4mwI3w=

notifications:
  slack: alexistest-workspace:ygssCOBT8NO8ImW4xBVasQZI